### ISSUE TITLE
你好, 非常有意义工作, 非常感谢您能提供论文的代码实现. 请问我该如何复现论文中的使用的基线模型的效果, 是否能提供使用的基线模型的代码? 非常感谢 :smile::smile: 

### ISSUE THREAD

**Issue by DuTim** [MC-CV/PKEF#1]
你好, 非常有意义工作, 非常感谢您能提供论文的代码实现. 请问我该如何复现论文中的使用的基线模型的效果, 是否能提供使用的基线模型的代码? 非常感谢 :smile::smile:

**Comment by MC-CV** [comment]
MF-BPR https://github.com/chinchi-hsu/KerasCollaborativeFiltering
NeuMF https://github.com/winterant/NeuralCollaborativeFiltering
LightGCN https://github.com/kuandeng/LightGCN
RGCN https://github.com/MichSchli/RelationPrediction
GNMR https://github.com/akaxlh/GNMR
NMTR https://github.com/tsinghua-fib-lab/NMTR
MBGCN https://github.com/tsinghua-fib-lab/MBGCN
CRGCN https://github.com/MingshiYan/CRGCN
MB-CGCN https://github.com/SS-00-SS/MBCGCN

**Comment by zengeng** [comment]
您好，非常感谢您的分享，我之前复现过您对比的mbcgcn，因为不太会效果不是很好，想请教一下您是如何复现的，期待您的回复，万分感谢！！！

**Comment by MC-CV** [comment]
感谢您的评论，这个问题可以问一下MBCGCN的作者。比这个结果更重要的是，我们的PKEF模型达到了更佳的效果，欢迎将我们的模型作为baseline。
