### ISSUE TITLE
关于baseline

### ISSUE THREAD

**Issue by zengeng** [MC-CV/PKEF#2]
请问mbcgcn您是如何运行的？期待您的回复！

**Comment by marqu22** [comment]
+1  it is very difficult to reproduce mbcgcn  experimental results, do the authors have any tips?

**Comment by MC-CV** [comment]
感谢你们的评论，这个问题可以问一下MBCGCN的作者。比这个结果更重要的是，我们的PKEF模型达到了更佳的效果，欢迎将我们的模型作为baseline。
