### ISSUE TITLE
Experimental setting issues

### ISSUE THREAD

**Issue by geonwooko** [MC-CV/PKEF#3]
In the paper, the embedding dimension is fixed to 64, but in the code it is set to 128. 
If I experiment this method with embedding dimension 64, it gets a poor score.

**Comment by MC-CV** [comment]
代码里面除以2了












霸道总柴
***@***.***


---Original---
From: "Geonwoo ***@***.***&gt;
Date: Tue, Apr 9, 2024 16:10 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [MC-CV/PKEF] Experimental setting issues (Issue #3)




 
In the paper, the embedding dimension is fixed to 64, but in the code it is set to 128.
 If I experiment this method with embedding dimension 64, it gets a poor score.

**Comment by MC-CV** [comment]
<img width="640" alt="image" src="https://github.com/MC-CV/PKEF/assets/78188024/8f8dd375-9402-4562-abdd-6efb223ecbd0">

**Comment by geonwooko** [comment]
Thank you
